jobs:
  coveralls:
    requires: [ ~pr, ~commit]
    image: node:12
    secrets:
      - COVERALLS_NODE_REPO_TOKEN
    environment:
      - COVERALLS_REPO_TOKEN: COVERALLS_NODE_REPO_TOKEN
    steps:
      - install: npm install
      - run: ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
